import React from "react";
import CustomNode from "./CustomNode";

var graphConfig = {
  "width": 800,
  "height": 400,
  "automaticRearrangeAfterDropNode": false,
  "collapsible": false,
  "directed": false,
  "focusAnimationDuration": 0.75,
  "focusZoom": 1,
  "freezeAllDragEvents": false,
  // "highlightDegree": 1,
  // "highlightOpacity": 1,
  // "linkHighlightBehavior": false,
  "maxZoom": 8,
  "minZoom": 0.1,
  "nodeHighlightBehavior": false,
  "panAndZoom": false,
  "staticGraph": false,
  "staticGraphWithDragAndDrop": false,
  "d3": {
    "alphaTarget": 0.05,
    "gravity": -400,
    "linkLength": 100,
    "linkStrength": 1,
    "disableLinkForce": true
  },

  "node": {
    "color": "#d3d3d3",
    "fontColor": "black",
    "fontSize": 12,
    // "fontWeight": "normal",
    // "highlightColor": "SAME",
    // "highlightFontSize": 8,
    // "highlightFontWeight": "normal",
    // "highlightStrokeColor": "SAME",
    // "highlightStrokeWidth": "SAME",
    "labelProperty": "id",
    "labelPosition": "left",
    "mouseCursor": "pointer",
    "opacity": 1,
    "renderLabel": false,
    "size": 320,
    "strokeColor": "none",
    "strokeWidth": 1.5,
    // "svg": "",
    // "symbolType": "circle",
    viewGenerator: node => <CustomNode token={node} />,
  },
  "link": {
    "color": "#d3d3d3",
    // "fontColor": "black",
    // "fontSize": 8,
    // "fontWeight": "normal",
    // "highlightColor": "SAME",
    // "highlightFontSize": 8,
    // "highlightFontWeight": "normal",
    "labelProperty": "label",
    "mouseCursor": "pointer",
    "opacity": 1,
    "renderLabel": false,
    "semanticStrokeWidth": false,
    "strokeWidth": 1,
    "markerHeight": 6,
    "markerWidth": 6,
    "strokeDasharray": 0,
    "strokeDashoffset": 0,
    "strokeLinecap": "butt",
    "type": "STRAIGHT" // CURVE_SMOOTH
  },
};

export default graphConfig;